sonar.projectKey=NoTIPswe_notip-data-consumer
sonar.organization=notipswe

sonar.sources=.
sonar.exclusions=**/*_test.go,vendor/**,**/Dockerfile*,**/*.dockerfile,**/*.yaml,**/*.yml,scripts/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
